### ISSUE TITLE
1주차 계획😊

### ISSUE THREAD

**Issue by shinhyogeun** [CodeSoom/project-react-3-shinhyogeun#1]
### YouTube API를 이용한 음악플레이어 프로젝트 

1. 이 앱을 언제 사용하나요?

음악을 듣고싶을 때 사용합니다. 다양한 노래들을 들어보세요.😊

  2. 구체적인 사례는 무엇인가요?

원하는 노래를 검색해요. 그 후에 그 노래를 재생목록에 추가할 수 있어요.

3. 이번주가 지나면 사용자는 무엇을 할 수 있나요?

노래를 검색하고 결과를 화면에서 확인할 수 있어요.

4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.

- [x] App에서 Search할 수 있게 SearchForm 생성 및 준비
- [x] API를 이용한 검색 결과 보여주기 구현
- [x] 결과를 보여줄 화면(MusicPage) 구현
- [x] 가벼운 플레이어 만들기

**Comment by Kihyun92** [comment]
1주차의 전략을 잘 세워보셨네요. 좋습니다! 😊

구상하신 서비스의 가장 중요한 가치가 무엇인지 생각해보시고, 그 핵심 가치를 아주 빠르게 전달해서 사용자들이 어떻게 생각하는지 피드백을 얻고 그 피드백을 통해 다시 가다듬어서 프로젝트를 완성해보는데 집중해보시면 좋을 것 같습니다~
