### ISSUE TITLE
2주차 계획🤔

### ISSUE THREAD

**Issue by shinhyogeun** [CodeSoom/project-react-3-shinhyogeun#33]
YouTube API를 이용한 음악플레이어 프로젝트

이 앱을 언제 사용하나요?
음악을 듣고싶을 때 사용합니다. 다양한 노래들을 들어보세요.😊

구체적인 사례는 무엇인가요?
원하는 노래를 검색해요. 그 후에 그 노래를 재생목록에 추가할 수 있어요.

이번주가 지나면 사용자는 무엇을 할 수 있나요?
노래를 검색하고 원하는 노래를 플레이어로 들을 수 있어요.

이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.

- [x] 노래를 재생하는 플레이어에 progressBar 구현
- [x] 노래길이가 5분보다 짧다면 1분 부분을 들을 수 있는 기능 추가
- [x] 소리조절 기능 추가
- [x] 전체적인 스타일을 입히기
- [x] 플레이리스트에 추가할 수 있는 기능 구현

**Comment by moonkii** [comment]
계획과 우선 순위도 잘 세우신 것 같아요.

매주 마다 새로 계획을 세우실 때 지난주 진행상황도 간단하게라도 명시해주시면 좋을 것 같아요 ;)
