### ISSUE TITLE
Youtube 영상의 시간을 조절하는 기능

### ISSUE THREAD

**Issue by shinhyogeun** [CodeSoom/project-react-3-shinhyogeun#35]
Youtube 영상이 시작되면 `onPlaying`이 실행되어 setTimeInterval(( ) => { }, 1000)로 재생시간을 계산합니다.

여기서 제약조건은 input의 range를 바꾼다면 바꿀때마다 `onPlaying`이 실행된다는 것입니다.

이렇게 된다면 input의 range를 채워서 영상을 끝내게 될 때 끝난 후에도 콜스택에 남아있는 `setTimeInterval`이 실행되어 재생시간이 약간 앞으로 당겨집니다.

(ex: 1:02:22 재생시간의 동영상에서 input의 range를 끝까지 밀면 재생시간이 1:02:22가 되어야하지만 1:00:01처럼 앞으로 조금 당겨짐.)

**Comment by moonkii** [comment]
콜스택에 남아있는 것들을 어떻게 제거해줄 수 있을까요?

**Comment by shinhyogeun** [comment]
영상이 끝날 때 (= `onEnd`가 실행될 때) `clearinterval`을 실행시켜 해결했습니다!
