### ISSUE TITLE
검색어 입력하고 엔터키를 눌러도 검색이 가능하게 해주는건 어떨까요?

### ISSUE THREAD

**Issue by Kihyun92** [CodeSoom/project-react-3-shinhyogeun#62]
몇가지 의견 남겨봅니다 ㅎㅎ

지금은 버튼을 클릭해야만 검색이되는 것 같은데, 검색어 입력후에 엔터키를 눌렀을때도 검색이 가능하면 좋을 것 같아요.

추가적으로 만약 유튜브와같이 초기 페이지에 추천 영상들이 들어가지 않을 예정이라면(지금같이) 검색란에 포커싱 되어있는 것도 사용성 측면에서 괜찮을 것 같아요.

**Comment by shinhyogeun** [comment]
지금 셔플기능을 구현하고있습니다~!! 이게 끝나고 업데이트 하겠습니다!! 피드백 감사합니다~!😊

**Comment by shinhyogeun** [comment]
구현완료 했습니다!
