### ISSUE TITLE
4주차 계획👍

### ISSUE THREAD

**Issue by shinhyogeun** [CodeSoom/project-react-3-shinhyogeun#73]
YouTube API를 이용한 음악플레이어 프로젝트

이 앱을 언제 사용하나요?
음악을 듣고싶을 때 사용합니다. 다양한 노래들을 들어보세요.😊

구체적인 사례는 무엇인가요?
원하는 노래를 검색해요. 그 후에 그 노래를 재생목록에 추가할 수 있어요.

이번주가 지나면 사용자는 무엇을 할 수 있나요?
사용자는 플레이리스트에서 음악을 자신만의 playlist에 추가할 수 있어요.

이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.

- [x] 하이라이트 듣기 아이콘을 삽입합니다.
- [x] 플레이리스트에 추가하면 추가되었다는 표시 모달을 넣어 보여줍니다.
- [x] 모달을 꾸밉니다.
- [x] 예상하지 못했던 오류들을 수정합니다.

벌써 코드숨의 마지막주이네요! 원래는 마지막에 여러개의 플레이리스트를 만들 수 있게 하려고하는 것을 해보려고 했지만 현재 만들어진 기능에도 고칠 것이 많아서 새로운 기능보다 현재 있는 기능의 완성도를 높이는 방향으로 마무리하려고 합니다! 감사합니다!😊

**Comment by moonkii** [comment]
말씀하신대로 기존에 구현하신 부분을 다듬어서 1차 배포라고 생각하시고 마무리하시면 좋을 것 같아요.
배포 후 사용성에 대한 피드백도 받아보고 지속적으로 업데이트해서 완성도를 높인다 생각하시면 될 것 같아요! ;)
